# Service manifect selector and post manifest label should be same. based on that label service (clusterip )can able to connect with pod


apiVersion: v1
kind: Pod
metadata:
 name: webapp1
 labels:
   app: webapp-resume1
 namespace: test-ns
spec:
  containers:
  - name: webapp1
    image: lokeshnagam121/javaproject
    ports:
    - containerPort: 8761

---

apiVersion: v1
kind: Service
metadata:
 name: webapp-svc
 namespace: test-ns
spec:
  type: NodePort
  selector:
   app: webapp-resume1
  ports:
  - port: 80
    targetPort: 8761
