# pod with 2 containers

apiVersion: v1
kind: Pod
metadata:
  name: testpod
  namespace: test-ns
  labels:
    app: testapp
spec:
  containers:
  - name: test-container1
    image: nginx
    ports:
    - containerPort: 8080
  - name: test-container2
    image: lokeshnagam121/javaproject
    ports:
    - containerPort: 8761

